<?php
session_start();
define('DS', DIRECTORY_SEPARATOR);
define('PATH_ROOT',str_replace('/admin', '', dirname(__FILE__) ) );
define('PATH_ROOT_WEB',str_replace('/admin', '', dirname(__FILE__) ) );
define('PATH_CACHE', PATH_ROOT.'/cache');
define('PATH_CONFIG', PATH_ROOT.'/config');
define('PATH_LOG', PATH_ROOT.'/logs');
define('PATH_SRC', PATH_ROOT.'/src');
define('PATH_TEMPLATES', PATH_ROOT.'/templates');
define('PATH_VENDOR', PATH_ROOT.'/vendor');
define('PATH_WEB', PATH_ROOT.'/web');
define('PATH_TEMPLATES_ADMIN', PATH_ROOT.'/admin/templates');
require_once PATH_VENDOR.'/autoload.php';
require_once PATH_CONFIG.'/clib.php';
require_once PATH_SRC.'/language/class.language.php';
require_once PATH_SRC.'/models/admin/model.admin.analytics.php';
require_once PATH_SRC.'/models/model.aplication.php';
require_once PATH_SRC.'/models/model.login.php';
require_once PATH_SRC.'/models/admin/model.admin.php';
require_once PATH_SRC.'/models/admin/model.admin.users.php';
require_once PATH_SRC.'/models/admin/model.admin.language.php';
require_once PATH_SRC.'/models/admin/model.admin.menus.php';
require_once PATH_SRC.'/models/admin/model.admin.camposfb.php';
require_once PATH_SRC.'/models/admin/model.templates.manager.php';
require_once PATH_SRC.'/models/admin/model.admin.install.template.php';
require_once PATH_SRC.'/phpmailer/class.phpmailer.php';
require_once PATH_SRC.'/logerror/class.log.php';
require_once PATH_SRC.'/controllers_admin/functions_admin.php';
$app = require PATH_SRC.'/bootstrap.admin.php';
require PATH_SRC.'/controllers_admin/controller.admin.php';
require PATH_SRC.'/controllers_admin/controller.admin.users.php';
require PATH_SRC.'/controllers_admin/controller.admin.menus.php';
require PATH_SRC.'/controllers_admin/controller.admin.language.php';
require PATH_SRC.'/controllers_admin/controller.admin.analytics.php';
require PATH_SRC.'/controllers_admin/controller.admin.camposfb.php';
require PATH_SRC.'/controllers_admin/controller.admin.templates.php';
$app['debug'] = false;
$app->run();
